/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AidescriptionRouteImport } from './routes/aidescription'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsTesteditRouteImport } from './routes/items/testedit'
import { Route as ItemsAddRouteImport } from './routes/items/add'
import { Route as ImgSplatRouteImport } from './routes/img.$'
import { Route as IItemIdRouteImport } from './routes/i.$itemId'
import { Route as ApiItemsRouteImport } from './routes/api/items'
import { Route as BackupDownloadSplatRouteImport } from './routes/backup.download.$'
import { Route as ApiE2eCreateSessionRouteImport } from './routes/api/e2e/create-session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ItemsItemIdLocationAddRouteImport } from './routes/items/$itemId/location/add'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AidescriptionRoute = AidescriptionRouteImport.update({
  id: '/aidescription',
  path: '/aidescription',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsTesteditRoute = ItemsTesteditRouteImport.update({
  id: '/items/testedit',
  path: '/items/testedit',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsAddRoute = ItemsAddRouteImport.update({
  id: '/items/add',
  path: '/items/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IItemIdRoute = IItemIdRouteImport.update({
  id: '/i/$itemId',
  path: '/i/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsRoute = ApiItemsRouteImport.update({
  id: '/api/items',
  path: '/api/items',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupDownloadSplatRoute = BackupDownloadSplatRouteImport.update({
  id: '/download/$',
  path: '/download/$',
  getParentRoute: () => BackupRoute,
} as any)
const ApiE2eCreateSessionRoute = ApiE2eCreateSessionRouteImport.update({
  id: '/api/e2e/create-session',
  path: '/api/e2e/create-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdLocationAddRoute = ItemsItemIdLocationAddRouteImport.update({
  id: '/items/$itemId/location/add',
  path: '/items/$itemId/location/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aidescription': typeof AidescriptionRoute
  '/backup': typeof BackupRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/api/items': typeof ApiItemsRoute
  '/i/$itemId': typeof IItemIdRoute
  '/img/$': typeof ImgSplatRoute
  '/items/add': typeof ItemsAddRoute
  '/items/testedit': typeof ItemsTesteditRoute
  '/items': typeof ItemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/create-session': typeof ApiE2eCreateSessionRoute
  '/backup/download/$': typeof BackupDownloadSplatRoute
  '/items/$itemId/location/add': typeof ItemsItemIdLocationAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aidescription': typeof AidescriptionRoute
  '/backup': typeof BackupRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/api/items': typeof ApiItemsRoute
  '/i/$itemId': typeof IItemIdRoute
  '/img/$': typeof ImgSplatRoute
  '/items/add': typeof ItemsAddRoute
  '/items/testedit': typeof ItemsTesteditRoute
  '/items': typeof ItemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/create-session': typeof ApiE2eCreateSessionRoute
  '/backup/download/$': typeof BackupDownloadSplatRoute
  '/items/$itemId/location/add': typeof ItemsItemIdLocationAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aidescription': typeof AidescriptionRoute
  '/backup': typeof BackupRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/api/items': typeof ApiItemsRoute
  '/i/$itemId': typeof IItemIdRoute
  '/img/$': typeof ImgSplatRoute
  '/items/add': typeof ItemsAddRoute
  '/items/testedit': typeof ItemsTesteditRoute
  '/items/': typeof ItemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/create-session': typeof ApiE2eCreateSessionRoute
  '/backup/download/$': typeof BackupDownloadSplatRoute
  '/items/$itemId/location/add': typeof ItemsItemIdLocationAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aidescription'
    | '/backup'
    | '/changelog'
    | '/locations'
    | '/login'
    | '/test'
    | '/api/items'
    | '/i/$itemId'
    | '/img/$'
    | '/items/add'
    | '/items/testedit'
    | '/items'
    | '/api/auth/$'
    | '/api/e2e/create-session'
    | '/backup/download/$'
    | '/items/$itemId/location/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aidescription'
    | '/backup'
    | '/changelog'
    | '/locations'
    | '/login'
    | '/test'
    | '/api/items'
    | '/i/$itemId'
    | '/img/$'
    | '/items/add'
    | '/items/testedit'
    | '/items'
    | '/api/auth/$'
    | '/api/e2e/create-session'
    | '/backup/download/$'
    | '/items/$itemId/location/add'
  id:
    | '__root__'
    | '/'
    | '/aidescription'
    | '/backup'
    | '/changelog'
    | '/locations'
    | '/login'
    | '/test'
    | '/api/items'
    | '/i/$itemId'
    | '/img/$'
    | '/items/add'
    | '/items/testedit'
    | '/items/'
    | '/api/auth/$'
    | '/api/e2e/create-session'
    | '/backup/download/$'
    | '/items/$itemId/location/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidescriptionRoute: typeof AidescriptionRoute
  BackupRoute: typeof BackupRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
  ApiItemsRoute: typeof ApiItemsRoute
  IItemIdRoute: typeof IItemIdRoute
  ImgSplatRoute: typeof ImgSplatRoute
  ItemsAddRoute: typeof ItemsAddRoute
  ItemsTesteditRoute: typeof ItemsTesteditRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiE2eCreateSessionRoute: typeof ApiE2eCreateSessionRoute
  ItemsItemIdLocationAddRoute: typeof ItemsItemIdLocationAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aidescription': {
      id: '/aidescription'
      path: '/aidescription'
      fullPath: '/aidescription'
      preLoaderRoute: typeof AidescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/testedit': {
      id: '/items/testedit'
      path: '/items/testedit'
      fullPath: '/items/testedit'
      preLoaderRoute: typeof ItemsTesteditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/add': {
      id: '/items/add'
      path: '/items/add'
      fullPath: '/items/add'
      preLoaderRoute: typeof ItemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$itemId': {
      id: '/i/$itemId'
      path: '/i/$itemId'
      fullPath: '/i/$itemId'
      preLoaderRoute: typeof IItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items': {
      id: '/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/download/$': {
      id: '/backup/download/$'
      path: '/download/$'
      fullPath: '/backup/download/$'
      preLoaderRoute: typeof BackupDownloadSplatRouteImport
      parentRoute: typeof BackupRoute
    }
    '/api/e2e/create-session': {
      id: '/api/e2e/create-session'
      path: '/api/e2e/create-session'
      fullPath: '/api/e2e/create-session'
      preLoaderRoute: typeof ApiE2eCreateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId/location/add': {
      id: '/items/$itemId/location/add'
      path: '/items/$itemId/location/add'
      fullPath: '/items/$itemId/location/add'
      preLoaderRoute: typeof ItemsItemIdLocationAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackupRouteChildren {
  BackupDownloadSplatRoute: typeof BackupDownloadSplatRoute
}

const BackupRouteChildren: BackupRouteChildren = {
  BackupDownloadSplatRoute: BackupDownloadSplatRoute,
}

const BackupRouteWithChildren =
  BackupRoute._addFileChildren(BackupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidescriptionRoute: AidescriptionRoute,
  BackupRoute: BackupRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
  ApiItemsRoute: ApiItemsRoute,
  IItemIdRoute: IItemIdRoute,
  ImgSplatRoute: ImgSplatRoute,
  ItemsAddRoute: ItemsAddRoute,
  ItemsTesteditRoute: ItemsTesteditRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiE2eCreateSessionRoute: ApiE2eCreateSessionRoute,
  ItemsItemIdLocationAddRoute: ItemsItemIdLocationAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
